- name: Add tailscale repo to helm
  kubernetes.core.helm_repository:
    name: tailscale
    repo_url: https://pkgs.tailscale.com/helmcharts
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Create values file
  ansible.builtin.include_role:
    name: helm_values
  vars:
    requested_values_templates:
      - tailscale

- name: Install tailscale operator via helm
  kubernetes.core.helm:
    name: tailscale-operator
    chart_ref: tailscale/tailscale-operator
    namespace: "{{ tailscale_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    state: present
