- name: Add vmware-tanzu (velero) repo to helm
  kubernetes.core.helm_repository:
    name: vmware-tanzu
    repo_url: https://vmware-tanzu.github.io/helm-charts
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Create values file
  ansible.builtin.include_role:
    name: helm_values
  vars:
    requested_values_templates:
      - velero

- name: Install velero via helm
  kubernetes.core.helm:
    name: velero
    chart_ref: vmware-tanzu/velero
    namespace: "{{ velero_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    values_files:
      - "{{ helm_values_temp_file }}"
    state: present

- name: Create access secret for velero
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloud-credentials
        namespace: "{{ velero_namespace }}"
      type: Opaque
      stringData:
        cloud: |
          [default]
          aws_access_key_id={{ minio_velero_tenant_access_key }}
          aws_secret_access_key={{ minio_velero_tenant_secret_key }}
    kubeconfig: "{{ k8s_kubectl_config_path }}"
  no_log: "{{ not debug }}"
