- name: Check if kublet is configured
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_configured

- name: Join k8s cluster
  ansible.builtin.include_tasks: k8s_join.yml
  when: "k8s_force_cluster_reset or k8s_worker_force_reset or not kubelet_configured.stat.exists"
