- name: Get hashicorp release signing key
  ansible.builtin.shell: 'curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg'
  become: true

- name: Add in apt source for hashicorp
  ansible.builtin.apt_repository:
    repo: 'deb [arch=arm64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com trixie main'
    state: present
    filename: 'hashicorp'
    update_cache: true
  become: true
