- name: Install calicoctl
  ansible.builtin.get_url:
    url: "https://github.com/projectcalico/calico/releases/download/v{{ k8s_cni_version }}/calicoctl-linux-arm64"
    dest: /usr/local/bin/kubectl-calico
    mode: 0755
  become: true
