- name: Add minio helm repo
  include_tasks: install_minio_repo.yml

- name: Install minio operator via helm
  include_tasks: install_minio_operator.yml

- name: Install minio-velero tenant via helm
  include_tasks: install_minio_velero_tenant.yml

- name: Create minio-velero tenant persistent storage
  include_tasks: create_minio_velero_storage.yml

- name: Add minio tenant api service address to hosts file
  include_tasks: add_minio_velero_svc_to_hosts.yml
