- name: Add projectcalico repo to helm
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Install calico via helm
  kubernetes.core.helm:
    name: projectcalico
    chart_ref: projectcalico/tigera-operator
    chart_version: "{{ k8s_cni_version }}"
    namespace: tigera-operator
    create_namespace: true
    release_values:
      installation:
        calicoNetwork:
          ipPools:
            - cidr: "{{ k8s_pod_network_cidr }}"
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    update_repo_cache: true
    state: present
