- name: Configure host dns
  ansible.builtin.include_tasks: configure_dns.yml

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: 'safe'
    state: 'latest'
    autoclean: true
    autoremove: true
  become: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  when: inventory_hostname is defined

- name: Configure patching
  ansible.builtin.include_tasks: configure_patching.yml

- name: Create temporary directory
  ansible.builtin.file:
    path: "{{ temp_directory }}"
    state: directory
    mode: 0755
