- name: Add openebs repo to helm
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: https://openebs.github.io/openebs
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    force_update: true

- name: Install openebs via helm
  kubernetes.core.helm:
    name: openebs
    chart_ref: openebs/openebs
    namespace: "{{ openebs_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_kubectl_config_path }}"
    release_values:
      engines:
        replicated:
          mayastor:
            enabled: false
      zfs-localpv:
        zfsNode:
          kubeletDir: /var/lib/kubelet
    update_repo_cache: true
    state: present
